# Generated by Django 6.0.2 on 2026-02-18 00:40

import django.db.models.deletion
import django.utils.timezone
import wallet.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ENEL', 'Enel (Luz)'), ('AGUAS_ANDINAS', 'Aguas Andinas (Agua)'), ('METROGAS', 'Metrogas (Gas)'), ('VTR', 'VTR (Internet/TV/Teléfono)'), ('MOVISTAR', 'Movistar (Internet/TV/Teléfono)'), ('CLARO', 'Claro (Internet/TV/Teléfono)'), ('MUNDO', 'Mundo (Internet/TV/Teléfono)'), ('AUTOPISTA_CENTRAL', 'Autopista Central (TAG)'), ('COSTANERA_NORTE', 'Costanera Norte (TAG)')], max_length=50)),
                ('logo', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Saldo Cuenta Corriente')),
                ('credit_line_limit', models.DecimalField(decimal_places=0, default=1000000, max_digits=12, verbose_name='Cupo Línea Crédito')),
                ('credit_line_usage', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Uso Línea Crédito')),
                ('account_number', models.CharField(default=wallet.models.generate_account_number, max_length=20, unique=True, verbose_name='Número de Cuenta')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('account_number', models.CharField(max_length=20, verbose_name='Número de Cuenta')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Destinatario')),
                ('bank', models.CharField(choices=[('BANCO_ESTADO', 'Banco Estado'), ('BANCO_CHILE', 'Banco de Chile'), ('SANTANDER', 'Banco Santander'), ('BCI', 'BCI'), ('SCOTIABANK', 'Scotiabank'), ('ITAU', 'Itaú'), ('FALABELLA', 'Banco Falabella'), ('RIPLEY', 'Banco Ripley'), ('SECURITY', 'Banco Security'), ('CONSORCIO', 'Banco Consorcio')], default='BANCO_ESTADO', max_length=50, verbose_name='Banco')),
                ('account_type', models.CharField(choices=[('CORRIENTE', 'Cuenta Corriente'), ('VISTA', 'Cuenta Vista / RUT'), ('AHORRO', 'Cuenta de Ahorro')], default='VISTA', max_length=20, verbose_name='Tipo de Cuenta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='4000123456789010', max_length=16)),
                ('cvv', models.CharField(default='123', max_length=3)),
                ('expiry', models.CharField(default='12/28', max_length=5)),
                ('issuer_image', models.CharField(default='visa_logo.png', max_length=100)),
                ('national_limit', models.DecimalField(decimal_places=0, default=500000, max_digits=12)),
                ('national_balance', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Deuda Nacional')),
                ('international_limit', models.DecimalField(decimal_places=2, default=1000.0, max_digits=12)),
                ('international_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Deuda Internacional USD')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_card', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Depósito'), ('TRANSFER', 'Transferencia'), ('PAY_SERVICE', 'Pago Servicio'), ('PAY_CARD', 'Pago Tarjeta')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
